apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-blocklist
  namespace: pihole 
data:
  BLOCKLIST_URLS: |-
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    https://adaway.org/hosts.txt
    https://v.firebog.net/hosts/AdguardDNS.txt