apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv 
  namespace: pihole 
spec: 
  claimRef:
    name: pihole-pvc
    namespace: pihole 
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle 