apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/Newell-ChristopherBrycen/GhostProjects/
    - Social:
        - Reddit:
            - icon: reddit.png
              href: https://reddit.com/
              description: The front page of the internet
    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
  services.yaml: |
    - My HomeLab:
        - ArgoCD
            href: http://argocd.cbc.io 
            description: Git Repo
        - GhostPath
            href: http://ghost.cbc.io 
            description: GL-B3000 Routing
        - AdGuard
            href: http://ghost.cbc.io:3000
            description: Ad blocker and more 

  widgets.yaml: |
    - logo:
        href: https://example.com
        target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        focus: true
        target: _blank
        showSearchSuggestions: true
  docker.yaml: ""
