apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/Newell-ChristopherBrycen/GhostProjects/
    - Social:
        - Reddit:
            - icon: reddit.png
              href: https://reddit.com/
    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
  services.yaml: |
    - HomeLab:
        - ArgoCD:
            href: http://argocd.cbc.io/
            description: CD Pipeline
        - GhostPath:
            href: http://ghost.cbc.io/
            description: GL-B3000 Routing
    - Entertainment:
        - Reddit:
            icon: reddit.png
            href: https://reddit.com/
        - YouTube:
            logo: youtube.png
            href: https://youtube.com/
  widgets.yaml: |
    - logo:
        href: https://reddit.com
        target: _blank
    - search:
        provider: duckduckgo
        focus: true
        target: _blank
        showSearchSuggestions: true
  docker.yaml: ""
