apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    gethomepage.dev/enabled: "false"
    gethomepage.dev/name: Homepage
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: homepage.cbc.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
