apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage-ingress-reader
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding
metadata:
  name: homepage-ingress-reader-binding
subjects:
- kind: ServiceAccount
  name: homepage
  namespace: homepage
roleRef:
  kind: ClusterRole
  name: homepage-ingress-reader
  apiGroup: rbac.authorization.k8s.io