apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
spec:
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  source:
    path: Applications/pihole
    repoURL: https://github.com/Newell-ChristopherBrycen/GhostProjects.git
    targetRevision: HEAD
  sources: []
  project: 'homelab'
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true