apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: 'homelab'
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  source:
    path: Applications/pihole
    repoURL: https://github.com/Newell-ChristopherBrycen/GhostProjects.git
    targetRevision: HEAD
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
