apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: 'homelab'
  source:
    repoURL: https://github.com/Newell-ChristopherBrycen/GhostProjects.git
    path: Applications/metallb
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
