apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: 
  name: my-app-set 
  namespace: argocd 
spec: 
  generators:
  - git:
      repoURL: https://github.com/Newell-ChristopherBrycen/GhostProjects.git
      revision: HEAD 
      directories:
      - path: 'Applications/*'
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    soruce:
      repoURL: https://github.com/Newell-ChristopherBrycen/GhostProjects.git
      targetRevision: HEAD
      path: '{{path}}
    destination: 
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true 