apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-controller-clusterrole
rules:
- apiGroups:
  - "" 
  resources:
  - configmaps
  - endpoints
  - secrets
  - services
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch